const HASH='7f4d776bd4386c614ca1b82cf3a9dde0a24a48879a87d2817afbbba03aff4f7e';
let D=DATA;try{const l=localStorage.getItem('prezData');if(l)D=JSON.parse(l)}catch(e){}
const V=['var(--ac)','var(--ac2)','var(--ac3)','var(--fg)'],$=s=>document.querySelector(s),esc=s=>String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;');
const qs=new URLSearchParams(location.search),slug=qs.get('c'),isT=qs.get('t');
const c=D.curente.find(x=>x.slug===slug),G=p=>p.split('.').reduce((o,k)=>o[k],c),E=p=>'<span class="ed" data-p="'+p+'">'+esc(G(p))+'</span>';
const save=()=>{try{localStorage.setItem('prezData',JSON.stringify(D))}catch(e){}};
async function sha(t){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(t));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
let EDIT=sessionStorage.getItem('ed')==='1';
function bar(){document.body.insertAdjacentHTML('beforeend','<div id="tb"><b>✎ Mod editare</b><span>textele marcate se pot modifica; se salvează în acest browser.</span><button class="btn p" id="dl">Descarcă data.js</button><button class="btn" id="rs">Resetează</button><button class="btn" id="ex">Ieși</button></div><button class="btn" id="lk" style="position:fixed;left:10px;bottom:10px;z-index:9">🔒 Editează</button>');
$('#lk').onclick=async()=>{if(EDIT)return;const pw=prompt('Parola:');if(pw&&await sha(pw)===HASH){sessionStorage.setItem('ed','1');location.reload()}else if(pw)alert('Parolă greșită')};
$('#ex').onclick=()=>{sessionStorage.removeItem('ed');location.reload()};
$('#rs').onclick=()=>{if(confirm('Ștergi modificările locale și revii la data.js din site?')){localStorage.removeItem('prezData');location.reload()}};
$('#dl').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['const DATA='+JSON.stringify(D,null,1)+';'],{type:'text/javascript'}));a.download='data.js';a.click()};
if(EDIT){document.body.classList.add('edit');$('#lk').style.display='none'}}
function arm(){if(!EDIT)return;document.querySelectorAll('.ed').forEach(e=>{e.contentEditable=true;e.oninput=()=>{const k=e.dataset.p.split('.'),l=k.pop();k.reduce((o,x)=>o[x],c)[l]=e.innerText;save()}})}
function face(s){let r=s*9301+49297;const R=()=>(r=(r*9301+49297)%233280)/233280,q=()=>V[Math.floor(R()*3)];return '<svg viewBox="0 0 200 200"><rect width="200" height="200" fill="'+q()+'" opacity=".25"/><path d="M40 200 Q100 120 160 200Z" fill="'+q()+'"/><ellipse cx="100" cy="88" rx="44" ry="56" fill="#fff" stroke="#2b2724" stroke-width="3"/><path d="M100 32 A44 56 0 0 1 100 144Z" fill="'+q()+'" opacity=".6"/><path d="M52 70 Q100 '+(10+R()*30)+' 148 70 L148 52 Q100 '+R()*20+' 52 52Z" fill="#2b2724"/><circle cx="82" cy="86" r="5"/><circle cx="118" cy="86" r="5"/><path d="M100 90 L92 116 L108 116Z" fill="none" stroke="#2b2724" stroke-width="3"/><path d="M84 132 Q100 140 116 132" fill="none" stroke="#2b2724" stroke-width="3"/></svg>'}
window.fb=(im,s)=>{im.parentNode.innerHTML=face(s)};
function art(sd){let r=sd*9301+49297;const R=()=>(r=(r*9301+49297)%233280)/233280;let h='';for(let k=0;k<16;k++){const x=R()*300,y=R()*300,w=40+R()*140,q=V[Math.floor(R()*4)],o=.25+R()*.6,t=Math.floor(R()*3);h+=t==0?'<rect x="'+x+'" y="'+y+'" width="'+w+'" height="'+w*(.4+R())+'" fill="'+q+'" opacity="'+o+'" transform="rotate('+(R()*40-20)+' '+x+' '+y+')"/>':t==1?'<polygon points="'+x+','+y+' '+(x+w)+','+(y+R()*60)+' '+(x+R()*w)+','+(y+w)+'" fill="'+q+'" opacity="'+o+'"/>':'<circle cx="'+(x+w/2)+'" cy="'+(y+w/2)+'" r="'+w/2.4+'" fill="none" stroke="'+q+'" stroke-width="'+(2+R()*5)+'" opacity="'+(o+.2)+'"/>'}return '<svg class="art" viewBox="0 0 400 400">'+h+'</svg>'}
function ring(path,n,R,big,ctr){let L='',N='';for(let i=0;i<n;i++){const a=i/n*6.283-1.57,r=big?R:(i%2?R+6:R-4),x=50+Math.cos(a)*r,y=50+Math.sin(a)*r;L+='<line x1="50" y1="50" x2="'+x+'" y2="'+y+'" stroke="'+V[i%3]+'" stroke-width=".5" '+(big?'':'stroke-dasharray="1.5 1.5"')+'/>';N+='<div class="nd'+(big?' big':'')+'" style="left:'+x+'%;top:'+y+'%;--c:'+V[i%3]+'">'+E(path+'.'+i)+'</div>'}return '<div class="ring"><svg viewBox="0 0 100 100">'+L+'</svg><div class="ctr">'+ctr+'</div>'+N+'</div>'}
const cd=(path,rows,f)=>'<div class="grid">'+rows.map((r,i)=>'<div class="card" style="--c:'+V[i%4]+'">'+f(r,i,path+'.'+i)+'</div>').join('')+'</div>';
function pres(){const n=D.curente.indexOf(c),S=[];
S.push('<div class="two"><div><span class="k">'+E('per')+'</span><h1>'+E('nume')+'</h1><p>Curentul '+(n+1)+' din '+D.curente.length+' · <a href="/">toate curentele</a></p><div class="by">Realizat de Ion Cocieru</div></div>'+art(n+1)+'</div>');
S.push('<span class="k">01 · Definiție</span><h2>Ce este '+esc(c.nume.toLowerCase())+'?</h2><div class="two"><div><p>'+E('def')+'</p></div>'+ring('cuvinte',c.cuvinte.length,34,0,esc(c.nume))+'</div>');
S.push('<span class="k">02 · Context istoric</span><h2>Contextul în care apare</h2><div class="tl">'+c.timeline.map((t,i)=>'<div><b>'+E('timeline.'+i+'.0')+'</b>'+E('timeline.'+i+'.1')+'</div>').join('')+'</div>'+cd('context',c.context,(r,i,p)=>'<b>'+E(p+'.0')+'</b><p>'+E(p+'.1')+'</p>'));
S.push('<span class="k">03 · Principii estetice</span><h2>Principii estetice</h2><div class="two">'+ring('principii',c.principii.length,36,1,'Principii estetice')+'<ul>'+c.pr.map((t,i)=>'<li>'+E('pr.'+i)+'</li>').join('')+'</ul></div>');
S.push('<span class="k">04 · Teme</span><h2>Teme și operele în care apar</h2><table><tr><th>Tema</th><th>Cum apare</th><th>Opere</th></tr>'+c.teme.map((r,i)=>'<tr>'+[0,1,2].map(j=>'<td>'+E('teme.'+i+'.'+j)+'</td>').join('')+'</tr>').join('')+'</table>');
S.push('<span class="k">04 · Motive</span><h2>Motive și operele în care apar</h2>'+cd('motive',c.motive,(r,i,p)=>'<b>'+E(p+'.0')+'</b><p>'+E(p+'.1')+'</p><p><em>'+E(p+'.2')+'</em></p>'));
S.push('<span class="k">05 · Valori</span><h2>Valorile curentului</h2>'+cd('valori',c.valori,(r,i,p)=>'<b>'+E(p+'.0')+'</b><p>'+E(p+'.1')+'</p>'));
S.push('<span class="k">06 · Genuri și specii</span><h2>Genuri și specii</h2><div style="text-align:center"><span class="root">'+esc(c.nume.toUpperCase())+'</span></div><div class="br">'+c.genuri.map((g,i)=>'<div class="card" style="--c:'+V[i]+'"><b>'+E('genuri.'+i+'.0')+'</b><div>'+g[1].map((s,j)=>'<span class="tag">'+E('genuri.'+i+'.1.'+j)+'</span>').join('')+'</div></div>').join('')+'</div>');
S.push('<span class="k">07 · Reprezentanți</span><h2>Autori de reținut</h2><div class="grid pp">'+c.autori.map((a,i)=>'<div class="port"><div class="im"><img src="/poze/'+encodeURI(a[3])+'" alt="" onerror="fb(this,'+(i+n*7)+')"></div><b>'+E('autori.'+i+'.0')+'</b><small>'+E('autori.'+i+'.1')+'<br>'+E('autori.'+i+'.2')+'</small></div>').join('')+'</div>');
S.push('<div style="text-align:center"><span class="k" style="transform:none">Testează-te</span><h2>Hai să vedem ce ai reținut</h2><p>Scanează codul și răspunde la întrebări.</p><div class="qr" style="margin:auto"><img src="/qr/'+slug+'.svg" alt="QR test"></div><p><a href="/test/'+slug+'">prezentari.vercel.app/test/'+slug+'</a></p><div class="by">Realizat de Ion Cocieru</div></div>');
document.body.innerHTML=S.map((h,i)=>'<section class="s'+(i?'':' on')+'">'+h+'</section>').join('')+'<nav><button id="p">‹</button><span id="cn"></span><button id="n">›</button></nav>';
const X=[...document.querySelectorAll('.s')];let i=0;const go=k=>{i=Math.max(0,Math.min(X.length-1,k));X.forEach((s,j)=>s.classList.toggle('on',j===i));$('#cn').textContent=(i+1)+' / '+X.length};
$('#p').onclick=()=>go(i-1);$('#n').onclick=()=>go(i+1);addEventListener('keydown',e=>{if(e.target.isContentEditable)return;if(['ArrowRight',' '].includes(e.key))go(i+1);if(e.key=='ArrowLeft')go(i-1)});go(0)}
function quiz(){const Q=c.test;let i=0,s=0,W=[];const m=document.body;
if(EDIT){m.innerHTML='<div class="qz"><span class="k">Editare test</span><h2>'+esc(c.nume)+'</h2>'+Q.map((q,k)=>'<div class="card" style="margin:18px 0"><p><b>'+(k+1)+'. '+E('test.'+k+'.0')+'</b></p>'+q[2].map((o,j)=>'<p>'+(j===q[1]?'✅ ':'▫️ ')+E('test.'+k+'.2.'+j)+' <button class="btn" data-k="'+k+'" data-j="'+j+'">corect</button></p>').join('')+'<p class="ex">Explicație: '+E('test.'+k+'.3')+'<br>De studiat: '+E('test.'+k+'.4')+'</p></div>').join('')+'<a href="/'+slug+'">← prezentarea</a></div>';
m.querySelectorAll('[data-k]').forEach(b=>b.onclick=()=>{Q[b.dataset.k][1]=+b.dataset.j;save();location.reload()});return}
const st=()=>{m.innerHTML='<div class="qz"><span class="k">Test · '+esc(c.nume)+'</span><h2>Cât de bine cunoști '+esc(c.nume.toLowerCase())+'?</h2><p>'+Q.length+' întrebări. La final afli rezultatul.</p><p class="ex">Realizat de Ion Cocieru</p><button class="btn p" id="go">Începe testul</button> <a href="/'+slug+'">← prezentarea</a></div>';$('#go').onclick=()=>{i=0;s=0;W=[];sh()}};
const sh=()=>{const q=Q[i];m.innerHTML='<div class="qz"><span class="k">Întrebarea '+(i+1)+' din '+Q.length+'</span><div class="bar"><i style="width:'+i/Q.length*100+'%"></i></div><h3 style="font-size:1.3rem">'+esc(q[0])+'</h3><div id="o"></div><div class="ex" id="e"></div><div id="nx"></div></div>';
q[2].forEach((t,j)=>{const b=document.createElement('button');b.className='o';b.textContent=t;b.onclick=()=>{const r=j===q[1];if(r)s++;else W.push(q[4]);document.querySelectorAll('.o').forEach((x,y)=>{x.disabled=true;if(y===q[1])x.classList.add('ok')});if(!r)b.classList.add('no');$('#e').textContent=(r?'Corect. ':'Greșit. ')+q[3];$('#nx').innerHTML='<button class="btn p">'+(i+1<Q.length?'Următoarea':'Vezi rezultatul')+'</button>';$('#nx').firstChild.onclick=()=>{i++;i<Q.length?sh():en()}};$('#o').appendChild(b)})};
const en=()=>{const p=Math.round(s/Q.length*100),e=p>=90?'🏆 Excelent! Ai înțeles foarte bine tema.':p>=70?'👍 Foarte bine! Mai ai câteva detalii de aprofundat.':p>=50?'📚 Bine, dar mai ai lacune. Aprofundează independent subiectele de mai jos.':'🔁 Mai ai de lucru. Studiază independent subiectele de mai jos și încearcă din nou.';
m.innerHTML='<div class="qz"><span class="k">Rezultat</span><h1 style="color:var(--ac)">'+s+'/'+Q.length+'</h1><h2>'+p+'%</h2><p>'+e+'</p>'+(W.length?'<div class="ex"><b>Ce mai ai de studiat independent:</b><ul>'+[...new Set(W)].map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul></div>':'')+'<button class="btn p" id="r">Reia testul</button> <a href="/">Alte curente</a></div>';$('#r').onclick=st};st()}
function index(){const L=D.curente.map((x,i)=>'<div class="card"><small>'+esc(x.per)+'</small><br><b>'+(i+1)+'. '+esc(x.nume)+'</b><p>'+esc(x.def.slice(0,130))+'…</p><div class="row"><a class="btn p" href="/'+x.slug+'">Prezentare</a><a class="btn" href="/test/'+x.slug+'">Test</a></div></div>').join('');
document.body.innerHTML='<div class="top"><span class="k">Literatură română și universală</span><h1>Curente literare</h1><p>De la umanism la postmodernism, în ordine cronologică. Fiecare curent are prezentare cu scheme și tabele, plus un test cu cod QR.</p><div class="by">Realizat de Ion Cocieru</div><div class="cl">'+L+'</div></div>'}
if(!slug)index();else if(!c)document.body.innerHTML='<div class="top"><h1>Pagina nu există</h1><a href="/">Înapoi</a></div>';else if(isT)quiz();else pres();
bar();arm();
